name: Queue tests

on:
  - push

jobs:
  queue:
    name: Queue application tests
    runs-on: ubuntu-latest
    steps:
      - name: Prepare composer version constraint prefix
        run: |
          BRANCH=${GITHUB_REF#refs/heads/}
          if [[ $BRANCH =~ ^[0-9]\.x$ ]]; then
            echo "VERSION_PREFIX=${BRANCH}-dev" >> $GITHUB_ENV
          else
            echo "VERSION_PREFIX=dev-${BRANCH}" >> $GITHUB_ENV
          fi

      - name: Clone test suite
        run: git clone https://github.com/archtechx/tenancy-queue-tester

      - name: Run tests
        run: |
          cd tenancy-queue-tester
          TENANCY_VERSION=${VERSION_PREFIX}#${GITHUB_SHA} ./setup.sh
          ./test.sh
          ./alternative_config.sh
          PERSISTENT=1 ./test.sh
